apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 100Mi
