apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: meshcentral
  name: meshcentral
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: meshcentral
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: meshcentral
    spec:
      containers:
        - image: ghcr.io/ylianst/meshcentral:1.1.27
          name: meshcentral
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 4433
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/meshcentral/meshcentral-data
              name: data
            - mountPath: /opt/meshcentral/meshcentral-files
              name: user-files
            - mountPath: /opt/meshcentral/meshcentral-backups
              name: backup
            - mountPath: /opt/meshcentral/meshcentral-web
              name: web
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: user-files
          persistentVolumeClaim:
            claimName: user-files
        - name: backup
          persistentVolumeClaim:
            claimName: backup
        - name: web
          persistentVolumeClaim:
            claimName: web
